// src/routes/about/+page.svelte
<script>
	import Icon from "@iconify/svelte";

  const clients = [
    { name: 'Bandit Machine', logo: '/clients/bandit-machine.png' }
  ];
</script>

<div class="text-gray-800 dark:text-white bg-white dark:bg-gray-800 py-3 px-4">
  <h1 class="text-3xl font-semibold pb-2">
    Who We Are
  </h1>
  <p class="text-xl">
    H2 Technologies is a technology solutions provider founded in 2023, headquarted in Ashland, OH.
    Our team comprises experienced professionals with deep expertise in software development, cloud solutions, and cybersecurity.
    We are committed to delivering high-quality, innovative solutions that meet the unique needs of our clients.
  </p>

</div>

<div class="text-gray-800 dark:text-white bg-gray-100 dark:bg-gray-900 py-3 px-4">
  <h1 class="text-3xl font-semibold pb-2">
    Mission
  </h1>
  <p class="text-xl">
    To empower businesses of all sizes with innovative technology solutions that drive growth, efficiency, and security.
  </p>
</div>

<div class="text-gray-800 dark:text-white bg-white dark:bg-gray-800 py-3 px-4">
  <h2 class="text-3xl font-semibold pb-2">
    Vision
  </h2>
  <p class="text-xl">
    To be a leading technology partner, recognized for our expertise, innovation, integrity, and commitment to customer success.
  </p>
</div>

<div class="text-gray-800 dark:text-white bg-gray-100 dark:bg-gray-900 py-3 px-4">
  <h2 class="text-3xl font-semibold pb-2">
    Values
  </h2>
  <div class="flex justify-center align-middle items-center">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4">
      <div class="bg-white dark:bg-gray-800 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Innovation
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8">
          We embrace necessary change and relentlessly seek novel approaches to solve complex problems.
        </p>
      </div>
      <div class="bg-white dark:bg-gray-800 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Customer Centricity
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8">
          We put our customers at the heart of everything we do.
        </p>
      </div>
      <div class="bg-white dark:bg-gray-800 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Integrity
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8">
          We conduct our business with honesty and transparency.
        </p>
      </div>
      <div class="bg-white dark:bg-gray-800 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Collaboration
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8">
          We believe in the power of teamwork and open communication.
        </p>
      </div>
      <div class="bg-white dark:bg-gray-800 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Excellence
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8">
          We strive for the highest standards in all our services and solutions.
        </p>
      </div>
      <div class="bg-white dark:bg-gray-800 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Adaptability
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8">
          We embrace change and continuously seek new ways to solve problems.
        </p>
      </div>

    </div>
  </div>
</div>

<div class="text-gray-800 dark:text-white bg-white dark:bg-gray-800 py-2">
  <h2 class="text-3xl font-semibold py-2">
    What We Do
  </h2>
  <div class="flex justify-center align-middle items-center">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4">
      <div class="bg-gray-100 dark:bg-gray-900 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Software and Website Development
        </h3>
        <p class="text-gray-600 dark:text-gray-300">
          We create custom software solutions and websites tailored to your business needs.
        </p>
      </div>
      <div class="bg-gray-100 dark:bg-gray-900 h-52 w-72 rounded-xl ">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Google Workspace Solutions
        </h3>
        <p class="text-gray-600 dark:text-gray-300 pt-8"> <!--TODO: Make this not bodged-->
          We provide tailored Google Workspace solutions to enhance your business's productivity and collaboration.
        </p>
      </div>
      <div class="bg-gray-100 dark:bg-gray-900 h-52 w-72 rounded-xl">
        <h3 class="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2 pt-4">
          Fortinet Equipment and Security Solutions
        </h3>
        <p class="text-gray-600 dark:text-gray-300">
          We provide Fortinet equipment and security solutions to protect your business from cyber threats while powering day to day operations.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="text-gray-800 dark:text-white bg-gray-100 dark:bg-gray-900 py-2 px-4">
  <h2 class="text-3xl font-semibold text-gray-800 dark:text-white text-center mb-2 pt-4">
    Our Clients
  </h2>
  <div class="flex flex-wrap justify-center gap-8 pt-2 pb-4">
    {#each clients as client}
      <div class="client-logo">
        <img
          src={client.logo}
          alt={client.name}
          class="h-16"
        />
      </div>
    {/each}
  </div>
</div>

<div class="bg-white dark:bg-gray-800 py-2 px-4 pb-8">
  <h2 class="text-3xl font-semibold text-gray-800 dark:text-white mb-4">
    Get in Touch
  </h2>
  <p class="text-gray-600 dark:text-gray-300 mb-8">
    We'd love to hear from you. Contact us today to learn more about how we
    can help your business.
  </p>
  <a href="/contact" class="bg-orange-500 hover:bg-orange-700 text-white font-bold py-3 px-8 rounded-md transition-colors duration-300">
    Contact Us
  </a>
</div>

// src/app/about/page.tsx
import { Icon } from "@iconify-icon/react";

const teamMembers = [
  {
    name: 'Austin Hadley',
    title: 'CEO',
    photo: '', // Replace with your actual image path
  },
  {
    name: 'Samuel Valencia',
    title: 'COO',
    photo: '', // Replace with your actual image path
  },
  {
    name: 'Eric Doepke',
    title: 'Junior Developer',
    photo: '', // Replace with your actual image path
  },
  {
    name: 'Joshua Lambert',
    title: 'Junior Designer',
    photo: '',
  },
  {
    name: 'Skyla Crislip',
    title: 'Junior Sales Associate',
    photo: '',
  },
];

const clients = [
  { name: 'Bandit Machine', logo: '/clients/bandit-machine.png' }
];

export default function AboutPage() {
  return (
    <main className="about-us-page">
      <header className="bg-gray-100 dark:bg-gray-900 py-16 text-center">
        <div className="container mx-auto">
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-800 dark:text-white">
            About Us
          </h1>
        </div>
      </header>

      <section className="company-overview py-16">
        <div className="container mx-auto space-y-8">
          <h2 className="text-3xl font-semibold text-gray-800 dark:text-white">
            Company Overview
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-2xl font-semibold text-gray-700 dark:text-gray-200">
                Our Mission
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                Our mission is to empower businesses with innovative technology
                solutions that drive growth, efficiency, and security.
              </p>
              <h3 className="text-2xl font-semibold text-gray-700 dark:text-gray-200 mt-6">
                Our Vision
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                To be a leading technology partner, recognized for our expertise,
                innovation, and commitment to client success.
              </p>
              <h3 className="text-2xl font-semibold text-gray-700 dark:text-gray-200 mt-6">
                Our Values
              </h3>
              <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-300">
                <li>Excellence</li>
                <li>Integrity</li>
                <li>Collaboration</li>
                <li>Innovation</li>
                <li>Customer Satisfaction</li>
              </ul>
            </div>
            <div>
              <h3 className="text-2xl font-semibold text-gray-700 dark:text-gray-200">
                Who We Are
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                H2 Technologies LLC is a technology solutions provider founded in 2023
                and headquartered in Ashland, OH. We have a rich history of
                helping businesses across various industries transform their
                operations with cutting-edge technology. Our team comprises
                experienced professionals with deep expertise in software
                development, cloud solutions, and cybersecurity.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="what-we-do py-16 bg-gray-100 dark:bg-gray-900">
        <div className="container mx-auto space-y-8">
          <h2 className="text-3xl font-semibold text-gray-800 dark:text-white text-center">
            What We Do
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2">
                Software and Website Development
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                We create custom software solutions and websites tailored to your
                business needs.
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2">
                Google Workspace Solutions
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                We provide comprehensive Google Workspace solutions to enhance
                productivity and collaboration.
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold text-gray-700 dark:text-gray-200 mb-2">
                Fortinet Equipment and Security Solutions
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                We offer Fortinet's industry-leading security products to protect
                your business from cyber threats.
              </p>
            </div>
          </div>
          <div>
            <h3 className="text-2xl font-semibold text-gray-700 dark:text-gray-200 text-center">
              Our Approach
            </h3>
            <p className="text-gray-600 dark:text-gray-300 text-center">
              We take a client-centric approach, working closely with our clients to
              understand their unique needs and deliver tailored solutions that
              exceed their expectations. We are committed to innovation, quality,
              and customer satisfaction.
            </p>
          </div>
        </div>
      </section>
      {
        teamMembers && teamMembers.length > 0 ?
          <section className="our-team py-16">
            <div className="container mx-auto space-y-8">
              <h2 className="text-3xl font-semibold text-gray-800 dark:text-white text-center">
                Meet Our Team
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {teamMembers.map((member) => (
                  <div key={member.name.replaceAll(" ", "_")} className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
                    {
                      member.photo.length > 0
                      ? <img src={member.photo} alt={member.name} className="rounded-full w-32 h-32 mx-auto mb-4" />
                      : <Icon icon="material-symbols:person-rounded" className="w-32 h-32 bg-slate-400 rounded-full mx-auto mb-4" />
                    }
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white text-center">
                      {member.name}
                    </h3>
                    <p className="text-gray-500 dark:text-gray-400 text-center mb-2">
                      {member.title}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </section>
          : null
      }

      {
        clients && clients.length > 0 ?
        <section className="our-clients py-16 bg-gray-100 dark:bg-gray-900">
          <div className="container mx-auto space-y-8">
            <h2 className="text-3xl font-semibold text-gray-800 dark:text-white text-center">
              Our Clients
            </h2>
            <div className="flex flex-wrap justify-center gap-8">
              {clients.map((client) => (
                <div key={client.name.replaceAll(" ", "-")} className="client-logo">
                  <img key={client.name.replaceAll(" ", "-")} src={client.logo} alt={client.name} className="h-16" />
                </div>
              ))}
            </div>
          </div>
        </section>
        : null
      }

      <section className="contact-information py-16">
        <div className="container mx-auto text-center">
          <h2 className="text-3xl font-semibold text-gray-800 dark:text-white mb-4">
            Get in Touch
          </h2>
          <p className="text-gray-600 dark:text-gray-300 mb-8">
            We'd love to hear from you. Contact us today to learn more about how we
            can help your business.
          </p>
          <a
            href="/contact"
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-md transition-colors duration-300"
          >
            Contact Us
          </a>
        </div>
      </section>
    </main>
  )
}
